{% set name = "freegenes" %}
{% set version = "0.0.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: decb49113a48cf33dacc96dda9e4885db5892ce9e24eee70fbcf5e7ec15a7c8f

build:
  number: 1
  entry_points:
    - freegenes=freegenes.client:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - pytest-runner
  run:
    - python >={{ python_min }}
    - requests >=2.21.0
    - semver >=2.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - freegenes
    - freegenes.main
    - freegenes.main.twist
    - freegenes.client
    - freegenes.client.shell
    - freegenes.client.twist
    - freegenes.logger
    - freegenes.logger.message
    - freegenes.logger.spinner
    - freegenes.tests
    - freegenes.utils
  commands:
    - freegenes --help

about:
  home: https://vsoch.github.io/freegenes-python
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Python API Client for FreeGenes Node
  doc_url: https://vsoch.github.io/freegenes-python
  dev_url: https://github.com/vsoch/freegenes-python

extra:
  recipe-maintainers:
    - vsoch
    - Koeng101
